### PR TITLE
fix build with upgrade to java parser 3.16.2

### PR DESCRIPTION
**Pull request by signed**
This is still work in progress and not ready to be reviewed.
Just want to run the CI.

### CODE REVIEW

**Comment by Bukama** [comment]
> This is still work in progress and not ready to be reviewed.
> 
> Just want to run the CI.

For such things, you can create an draft-PR. You can also convert an open PR into a draft (and vice versa of course :) )

**Comment by signed** [comment]
@Bukama thank you for sharing. I was not aware that this feature exists 😮

**Comment by Bukama** [comment]
> @Bukama thank you for sharing. I was not aware that this feature exists 😮

I didn't know for a long time either, but I really like it :)

**Comment by signed** [comment]
with the new release of javaparser this is finally working.
Some minor empty space reformatting changes, but nothing major.

**Review by Bukama — APPROVED** [review]

**Pull request merged**
