### PR TITLE
enable Dependabot v2

### PR DESCRIPTION
**Pull request by sullis**
https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

### CODE REVIEW

**Comment by signed** [comment]
Thank you for the PR. I have not used dependabot outside of the security update feature.
I like to take a look at the configuration options available before merging the PR, no promises when this will happen.

**Comment by Bukama** [comment]
Before we will eventually merge this, we will decide if we want to use ddpendabot at all (see referenced issue). So see this as „on hold / in discussion“. 

In general we appreciate that there is an issue on which a PR is based on.

**Review by Bukama — CHANGES_REQUESTED** [review]
We decided (see https://github.com/junit-pioneer/junit-pioneer/issues/315 ) to use dependabot with the following settings:

* Gradle
* Github actions
* Monthly updates
* No dependencies, especially not JUnit

An example can be seen here: https://github.com/junit-pioneer/junit-pioneer/pull/337

So please update the PR, thanks

**Comment by sullis** [comment]
> So please update the PR, thanks

I just updated dependabot.yml --- I copied the file from the junit-pioneer repo.

**Comment by signed** [comment]
I'm looking into the failing ci on windows.

**Comment by signed** [comment]
Thank your for the PR.
Sorry that it took so long. Had to fix the builds first.

**Pull request merged**
